import type {
  Home,
  Host,
  Guest,
  HomeRequest,
  Payment,
  Review,
  Notification,
  SaleOffer,
  RentalContract,
} from "./types"

export const hosts: Host[] = [
  {
    id: "h1",
    firstName: "Alexander",
    lastName: "Petrov",
    dateOfBirth: "1985-03-15",
    email: "alexander.petrov@email.com",
    phoneNumber: "+998901234567",
    gender: "Male",
  },
  {
    id: "h2",
    firstName: "Maria",
    lastName: "Ivanova",
    dateOfBirth: "1990-07-22",
    email: "maria.ivanova@email.com",
    phoneNumber: "+998901234568",
    gender: "Female",
  },
  {
    id: "h3",
    firstName: "David",
    lastName: "Kim",
    dateOfBirth: "1982-11-08",
    email: "david.kim@email.com",
    phoneNumber: "+998901234569",
    gender: "Male",
  },
]

export const guests: Guest[] = [
  {
    id: "g1",
    firstName: "Emily",
    lastName: "Chen",
    dateOfBirth: "1995-01-10",
    email: "emily.chen@email.com",
    phoneNumber: "+998901234570",
    address: "123 Oak Street",
    gender: "Female",
  },
  {
    id: "g2",
    firstName: "James",
    lastName: "Wilson",
    dateOfBirth: "1988-05-20",
    email: "james.wilson@email.com",
    phoneNumber: "+998901234571",
    address: "456 Maple Avenue",
    gender: "Male",
  },
  {
    id: "g3",
    firstName: "Sofia",
    lastName: "Rodriguez",
    dateOfBirth: "1992-09-14",
    email: "sofia.rodriguez@email.com",
    phoneNumber: "+998901234572",
    address: "789 Pine Road",
    gender: "Female",
  },
  {
    id: "g4",
    firstName: "Liam",
    lastName: "Nguyen",
    dateOfBirth: "1991-12-03",
    email: "liam.nguyen@email.com",
    phoneNumber: "+998901234573",
    address: "321 Cedar Lane",
    gender: "Male",
  },
]

export const homes: Home[] = [
  {
    id: "home1",
    hostId: "h1",
    address: "42 Sunset Boulevard, Tashkent",
    additionalInfo:
      "Luxury apartment with panoramic city views, modern furnishing, and 24/7 security.",
    isVacant: true,
    isPetAllowed: true,
    isShared: false,
    numberOfBedrooms: 3,
    numberOfBathrooms: 2,
    area: 120,
    type: "Flat",
    listingType: "ForRent",
    monthlyRent: 1200,
    securityDeposit: 2400,
    imageUrls: "/images/homes/home-1.jpg",
    isFeatured: true,
    host: hosts[0],
    createdDate: "2025-12-01",
    updatedDate: "2026-01-15",
  },
  {
    id: "home2",
    hostId: "h2",
    address: "18 Garden Street, Samarkand",
    additionalInfo:
      "Cozy family house with spacious backyard, garage, and recently renovated kitchen.",
    isVacant: true,
    isPetAllowed: true,
    isShared: false,
    numberOfBedrooms: 4,
    numberOfBathrooms: 3,
    area: 220,
    type: "Bungalow",
    listingType: "ForSale",
    salePrice: 350000,
    imageUrls: "/images/homes/home-2.jpg",
    isFeatured: true,
    host: hosts[1],
    createdDate: "2025-11-20",
    updatedDate: "2026-01-10",
  },
  {
    id: "home3",
    hostId: "h3",
    address: "7 Ocean Drive, Bukhara",
    additionalInfo:
      "Modern villa with private pool, landscaped garden, and smart home features.",
    isVacant: true,
    isPetAllowed: false,
    isShared: false,
    numberOfBedrooms: 5,
    numberOfBathrooms: 4,
    area: 380,
    type: "Villa",
    listingType: "ForSale",
    salePrice: 890000,
    imageUrls: "/images/homes/home-3.jpg",
    isFeatured: true,
    host: hosts[2],
    createdDate: "2025-10-05",
    updatedDate: "2026-02-01",
  },
  {
    id: "home4",
    hostId: "h1",
    address: "55 Main Avenue, Tashkent",
    additionalInfo:
      "Elegant townhouse in the city center with rooftop terrace and private parking.",
    isVacant: false,
    isPetAllowed: true,
    isShared: false,
    numberOfBedrooms: 3,
    numberOfBathrooms: 2,
    area: 160,
    type: "Townhouse",
    listingType: "ForRent",
    monthlyRent: 950,
    securityDeposit: 1900,
    imageUrls: "/images/homes/home-4.jpg",
    isFeatured: true,
    host: hosts[0],
    createdDate: "2025-09-15",
    updatedDate: "2026-01-20",
  },
  {
    id: "home5",
    hostId: "h2",
    address: "12 River Lane, Fergana",
    additionalInfo:
      "Modern studio apartment, perfect for professionals, fully furnished with city views.",
    isVacant: true,
    isPetAllowed: false,
    isShared: false,
    numberOfBedrooms: 1,
    numberOfBathrooms: 1,
    area: 45,
    type: "Studio",
    listingType: "ForRent",
    monthlyRent: 600,
    securityDeposit: 1200,
    imageUrls: "/images/homes/home-5.jpg",
    isFeatured: false,
    host: hosts[1],
    createdDate: "2026-01-05",
    updatedDate: "2026-02-10",
  },
  {
    id: "home6",
    hostId: "h3",
    address: "88 Skyline Towers, Tashkent",
    additionalInfo:
      "Stunning penthouse with 360-degree views, private elevator, and luxury finishes.",
    isVacant: true,
    isPetAllowed: true,
    isShared: false,
    numberOfBedrooms: 4,
    numberOfBathrooms: 3,
    area: 280,
    type: "Penthouse",
    listingType: "Both",
    monthlyRent: 3500,
    salePrice: 1200000,
    securityDeposit: 7000,
    imageUrls: "/images/homes/home-6.jpg",
    isFeatured: true,
    host: hosts[2],
    createdDate: "2026-01-15",
    updatedDate: "2026-02-20",
  },
]

export const homeRequests: HomeRequest[] = [
  {
    id: "req1",
    guestId: "g1",
    homeId: "home1",
    message: "I am interested in renting this apartment for 6 months.",
    startDate: "2026-03-01",
    endDate: "2026-09-01",
    createdDate: "2026-02-15",
    updatedDate: "2026-02-15",
    status: "Pending",
    guest: guests[0],
    home: homes[0],
  },
  {
    id: "req2",
    guestId: "g2",
    homeId: "home3",
    message: "Would love to schedule a viewing for this villa.",
    startDate: "2026-04-01",
    endDate: "2026-04-01",
    createdDate: "2026-02-10",
    updatedDate: "2026-02-12",
    status: "Approved",
    guest: guests[1],
    home: homes[2],
  },
  {
    id: "req3",
    guestId: "g3",
    homeId: "home5",
    message: "Looking for a studio for my work assignment.",
    startDate: "2026-03-15",
    endDate: "2026-12-15",
    createdDate: "2026-02-18",
    updatedDate: "2026-02-18",
    status: "Pending",
    guest: guests[2],
    home: homes[4],
  },
  {
    id: "req4",
    guestId: "g4",
    homeId: "home4",
    message: "Interested but need to discuss the terms.",
    startDate: "2026-02-01",
    endDate: "2026-08-01",
    createdDate: "2026-01-20",
    updatedDate: "2026-01-25",
    status: "Rejected",
    rejectionReason: "Property already under contract.",
    guest: guests[3],
    home: homes[3],
  },
]

export const payments: Payment[] = [
  {
    id: "pay1",
    userId: "g1",
    rentalContractId: "rc1",
    amount: 1200,
    method: "BankTransfer",
    status: "Completed",
    paymentDate: "2026-02-01",
    transactionReference: "TXN-20260201-001",
    createdDate: "2026-02-01",
    updatedDate: "2026-02-01",
  },
  {
    id: "pay2",
    userId: "g2",
    saleTransactionId: "st1",
    amount: 350000,
    method: "BankTransfer",
    status: "Completed",
    paymentDate: "2026-01-15",
    transactionReference: "TXN-20260115-002",
    createdDate: "2026-01-15",
    updatedDate: "2026-01-15",
  },
  {
    id: "pay3",
    userId: "g3",
    rentalContractId: "rc2",
    amount: 600,
    method: "Card",
    status: "Pending",
    paymentDate: "2026-02-20",
    transactionReference: "TXN-20260220-003",
    createdDate: "2026-02-20",
    updatedDate: "2026-02-20",
  },
  {
    id: "pay4",
    userId: "g4",
    rentalContractId: "rc3",
    amount: 950,
    method: "Cash",
    status: "Failed",
    paymentDate: "2026-02-18",
    transactionReference: "TXN-20260218-004",
    createdDate: "2026-02-18",
    updatedDate: "2026-02-18",
  },
]

export const reviews: Review[] = [
  {
    id: "rev1",
    homeId: "home1",
    guestId: "g1",
    rating: 5,
    comment:
      "Absolutely stunning apartment with incredible views. The host was very responsive and helpful.",
    createdDate: "2026-01-20",
    guest: guests[0],
    home: homes[0],
  },
  {
    id: "rev2",
    homeId: "home2",
    guestId: "g2",
    rating: 4,
    comment:
      "Beautiful house with a great garden. Perfect for families. Just needs minor updates in the bathroom.",
    createdDate: "2026-01-25",
    guest: guests[1],
    home: homes[1],
  },
  {
    id: "rev3",
    homeId: "home3",
    guestId: "g3",
    rating: 5,
    comment:
      "The villa exceeded all expectations. The pool area and smart home features are top-notch.",
    createdDate: "2026-02-05",
    guest: guests[2],
    home: homes[2],
  },
  {
    id: "rev4",
    homeId: "home5",
    guestId: "g4",
    rating: 3,
    comment:
      "Good location and modern design, but the studio feels a bit smaller than expected.",
    createdDate: "2026-02-10",
    guest: guests[3],
    home: homes[4],
  },
]

export const notifications: Notification[] = [
  {
    id: "n1",
    userId: "admin",
    title: "New Home Request",
    message:
      "Emily Chen has submitted a new rental request for 42 Sunset Boulevard.",
    type: "Request",
    isRead: false,
    createdDate: "2026-02-15T10:30:00",
  },
  {
    id: "n2",
    userId: "admin",
    title: "Payment Received",
    message:
      "Payment of $1,200 received from Emily Chen for rental contract RC-001.",
    type: "Payment",
    isRead: false,
    createdDate: "2026-02-14T14:20:00",
  },
  {
    id: "n3",
    userId: "admin",
    title: "New Review Posted",
    message: "Sofia Rodriguez posted a 5-star review for 7 Ocean Drive villa.",
    type: "Review",
    isRead: true,
    createdDate: "2026-02-13T09:15:00",
  },
  {
    id: "n4",
    userId: "admin",
    title: "Property Listed",
    message: "New penthouse at 88 Skyline Towers has been listed successfully.",
    type: "Listing",
    isRead: true,
    createdDate: "2026-02-12T16:45:00",
  },
]

export const saleOffers: SaleOffer[] = [
  {
    id: "so1",
    homeId: "home2",
    guestId: "g2",
    offerAmount: 340000,
    message: "I would like to offer $340,000 for this property.",
    status: "Pending",
    createdDate: "2026-02-10",
    guest: guests[1],
    home: homes[1],
  },
  {
    id: "so2",
    homeId: "home3",
    guestId: "g3",
    offerAmount: 860000,
    message: "Offering $860,000, ready for immediate purchase.",
    status: "Approved",
    createdDate: "2026-02-08",
    guest: guests[2],
    home: homes[2],
  },
  {
    id: "so3",
    homeId: "home6",
    guestId: "g4",
    offerAmount: 1100000,
    message: "Interested in purchasing the penthouse.",
    status: "Pending",
    createdDate: "2026-02-18",
    guest: guests[3],
    home: homes[5],
  },
]

export const rentalContracts: RentalContract[] = [
  {
    id: "rc1",
    homeId: "home1",
    guestId: "g1",
    startDate: "2026-01-01",
    endDate: "2026-07-01",
    monthlyRent: 1200,
    securityDeposit: 2400,
    status: "Active",
    createdDate: "2025-12-20",
    guest: guests[0],
    home: homes[0],
  },
  {
    id: "rc2",
    homeId: "home5",
    guestId: "g3",
    startDate: "2026-02-01",
    endDate: "2026-08-01",
    monthlyRent: 600,
    securityDeposit: 1200,
    status: "Active",
    createdDate: "2026-01-25",
    guest: guests[2],
    home: homes[4],
  },
  {
    id: "rc3",
    homeId: "home4",
    guestId: "g4",
    startDate: "2025-09-01",
    endDate: "2026-03-01",
    monthlyRent: 950,
    securityDeposit: 1900,
    status: "Expiring",
    createdDate: "2025-08-20",
    guest: guests[3],
    home: homes[3],
  },
]

export const dashboardStats = {
  totalHomes: homes.length,
  totalHosts: hosts.length,
  activeGuests: guests.length,
  totalTransactions: payments.filter((p) => p.status === "Completed").length,
  totalRevenue: payments
    .filter((p) => p.status === "Completed")
    .reduce((sum, p) => sum + p.amount, 0),
  pendingRequests: homeRequests.filter((r) => r.status === "Pending").length,
}
